version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: kerro
      POSTGRES_PASSWORD: ambientepruebas
      POSTGRES_DB: inventario
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 15432:5432

  backend:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/inventario
      SPRING_DATASOURCE_USERNAME: kerro
      SPRING_DATASOURCE_PASSWORD: ambientepruebas
    ports:
      - 8080:8080

volumes:
  pgdata: